version: "3.8"

services:

  medilabo-frontapp:
    build: ./medilabo-frontapp
    image: medilabo-frontapp
    container_name: medilabo-frontapp
    ports:
      - 18080:8080
    environment:
      MS_GATEWAY_URL: medilabo-gateway:8081
    networks:
      - medilabo_network

  medilabo-gateway:
    build: ./medilabo-gateway
    image: medilabo-gateway
    container_name: medilabo-gateway
    ports:
      - 18081:8081
    environment:
      MS_GATEWAY_URI: medilabo-gateway:8081
      MS_PATIENT_URI: medilabo-patientapp:8082
    networks:
      - medilabo_network

  medilabo-patient:
    build: ./medilabo-patientapp
    image: medilabo-patientapp
    container_name: medilabo-patientapp
    depends_on:
       mysqldb:
          condition: service_healthy
    ports:
      - 18082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://medilabo-patientapp-db:13306/patients?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql!
    networks:
      - medilabo_network
      
  mysqldb:
    image: mysql:8.0.13
    container_name: medilabo-patientapp-db
    environment:
      MYSQL_TCP_PORT: 13306
      MYSQL_ROOT_PASSWORD: mysql!
      MYSQL_DATABASE: patients
      MYSQL_PASSWORD: mysql!
    ports:
      - 13306:13306
    healthcheck:
       test: ["CMD-SHELL", "mysqladmin ping -p$$MYSQL_PASSWORD | grep alive || exit 1"]
       interval: 20s
       timeout: 10s
       retries: 2
       start_period: 5s
    networks:
      - medilabo_network
    volumes: 
       - mysqldbdata:/var/lib/mysql     
    
networks:
  medilabo_network:
    driver: bridge

volumes:
   mysqldbdata: