version: "3.8"

services:

  medilabo-patient:
    image: medilabo-patientapp
    container_name: medilabo-patientapp
    depends_on:
       mysqldb:
          condition: service_healthy
    ports:
      - 18082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/patients?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql!
    networks:
      - medilabo_network
      
  mysqldb:
    image: mysql:8.0.13
    container_name: medilabo-patientapp-db
    environment:
      DATABASE_HOST: patients
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: mysql!
      MYSQL_DATABASE: patients
      MYSQL_PASSWORD: mysql!
    healthcheck:
       test: ["CMD-SHELL", "mysqladmin ping -p$$MYSQL_PASSWORD | grep alive || exit 1"]
       interval: 20s
       timeout: 10s
       retries: 2
       start_period: 10s
    networks:
      - medilabo_network
    volumes: 
       - mysqldbdata:/var/lib/mysql     
    
networks:
  medilabo_network:
    driver: bridge

volumes:
   mysqldbdata: